Creados los árboles que spawnean armas
Tai1Games/Programa-de-Convivencia-Espacial pull request #107
Opened 2020-04-26 01:44 UTC by Pj6595

### Árboles de spawns

Se han creado los árboles que spawnean armas. La gracia es que va apareciendo el arma en cuestión y se va haciendo grande hasta que pasa el tiempo de spawn y se puede utilizar.

**CLASE SPAWNTREE**
Los árboles están en la capa UninteractableObject. La posición desde la que spawnean las cosas es un poco provisional porque no sé exactamente cómo va a ser el árbol/maceta/loquesea que vaya a ser esto al final, la ajustaré cuando se sepa.

**CLASE WEAPONPOOL**
Para que los árboles puedan spawnear armas de cualquier pool de armas, se ha creado la clase WeaponPool de la que heredarán todas las pools de objetos que vayan a spawnear de árboles. Básicamente es un interfaz que permite que por polimorfismo podamos pasarle al árbol cualquier pool de armas y funcione bien sin necesidad de más movidas chungas, toda la funcionalidad sigue estando en la clase específica de cada pool.

QUEDA POR HACER:

>La cosa del componente para lo del modo por tiempo
>Descubrir por qué los tomates chocan con los roombas
>Que se apruebe lo de los tomates de MMur

2020-04-26 17:22 UTC, JuanmaSalva submitted a review, later dismissed

2020-05-01 15:38 UTC, AndresRuizB reviewed
Sigue así pejota ;D

2020-05-10 10:35 UTC, JuanmaSalva approved these changes
el platano esta roto :(

2020-05-10 12:26 UTC, EstebenR requested changes
Los archivos de TomatoTree estan comentados enteros??

En StocksGameMode sigue estando el need to delete, linea 17

2020-05-10 12:26 UTC, EstebenR commented on src/SourceFiles/TimeGameMode.h
> +	TomatoPool tomatoPool_;
Esto deberia estar aqui?

2020-05-10 12:26 UTC, EstebenR commented on src/SourceFiles/CapitalismGameMode.cpp
> +#include "BananaPool.h"
Los pools hace falta incluirlos? Por que en el resto de gamemodes no?

2020-05-10 16:37 UTC, JuanmaSalva approved these changes
ahora si, antes lo habia aceptado aun q habia algo roto por q soy retrasado y me habia equivocado de boton

2020-05-10 16:57 UTC, Adrian-de-Lucas-Gomez approved these changes
Nice

2020-05-10 17:25 UTC, EstebenR requested changes
Al disparar el platano no sale proyectil

2020-05-10 17:29 UTC, EstebenR approved these changes

2020-05-10 17:29 UTC, merged