[Delivers-#172456305] Keyboard Input e InputBinder
Tai1Games/Programa-de-Convivencia-Espacial pull request #111
Opened 2020-04-26 16:08 UTC by AdriAlvarez00

### InputBinder
Ya no se pide input a InputHandler! ahora se pide una acción a InputBindery por polimorfismo pedirá lo necesario. Por ahora los controles son fijos pero se podría cambiar más adelante.
El Binder de los jugadores se consigue pidiéndoselo a PlayerData::getBinder().
### Otros cambios
- Cambios en Weapon para que pueda pedir el input que corresponde a los binders de cada jugador en rango.
- InputHandler ahora devuelve valores por defecto si le pides input de un mando que no existe así que ya se pueden instanciar hasta 4 jugadores con sus Hands y todos los componentes sin que haya problemas.
- Por defecto se crea un ControllerBinder en el constructor de Playerdata, en el futuro habría que hacer un lobby y pasarle el Binder de controles por parámetro

2020-04-26 17:08 UTC, JuanmaSalva approved these changes

2020-04-26 17:55 UTC, EstebenR requested changes
Puro teclado no admite dos jugadores :c

also se puede hacer que si conectas un mando despues de empezar el juego lo detecte? (no es obligatorio)

2020-04-26 17:55 UTC, EstebenR commented on src/SourceFiles/PlayerController.cpp
> +	ib = GETCMP1_(PlayerData)->getBinder();
ya has polleado el playerData arriba xd

2020-04-26 17:55 UTC, EstebenR commented on src/SourceFiles/InputHandler.h
> +	std::array<ButtonState, 1000> kbState_;
por que existe un array de 1000 unidades de buttonState? Jesusito llora

2020-04-26 17:55 UTC, EstebenR commented on src/SourceFiles/InputHandler.cpp
>  	}
Esto se llama cada update adri donde te sentaste D:

2020-04-26 18:11 UTC, AdriAlvarez00 commented on src/SourceFiles/InputHandler.h
> +	std::array<ButtonState, 1000> kbState_;
Puedo ir probando a bajar el tamaño, el problema es que SDL no deja claro cuantas posibles teclas pueden funcionar, puedo probar a ir bajando pero es posible que un array de 100/200 haya que tener

2020-04-26 18:12 UTC, AdriAlvarez00 commented on src/SourceFiles/InputHandler.cpp
>  	}
1.- Voy a intentar reducir el tamaño del array en lo posible
2.- Puedo probar a cachear las variables i en unos arrays de just up y just down y asi el coste pasa de ser lineal en teclas de teclado a lineal en teclas recien pulsadas o soltadas

2020-04-26 19:40 UTC, EstebenR requested changes
No se ven los impulsos etc

2020-04-26 19:47 UTC, EstebenR requested changes
la mano no se mueve con teclado adrian >:c

2020-04-27 11:03 UTC, EstebenR requested changes
No guarda bien el último angulo en teclado, por ejemplo si sueltas wasd la direccion del impulso es 0

2020-04-28 09:22 UTC, EstebenR requested changes
para tirar un arma recogida hay que mantener el boton varios frames por alguna razon.

La constructora de KeyboardMouse si le paso CMP1(Collider) me da error de compilacion

2020-04-28 09:52 UTC, EstebenR approved these changes

2020-04-28 10:49 UTC, Pj6595 approved these changes

2020-04-28 10:49 UTC, merged