171293032 planta carnivora
Tai1Games/Programa-de-Convivencia-Espacial pull request #112
Opened 2020-04-26 18:09 UTC by JuanmaSalva

Cosas añadidas:
Clase carnivourousPlant
Animación cutre

Como funciona:
hay un temporizador en milisegundos que al llegar a 0 te come. Se puede ver como va quedando menos tiempo por que la animacion idle de la planta va cada vez mas rápido. Si entras, pasas 1 segundo y sales, cuando vuelvas a entrar el tiempo sigue desde ese segundo, no se resetea. Si hay dos jugadores la hostia se la lleva el ultimo en entrar por imbécil.
Aparece en el GYM por q no tenemos jardín pero va con tiled asi q es solo cambiarlo desde alli.

Creo q eso es todo, tengo pesadillas con esto

2020-04-26 20:54 UTC, Pj6595 approved these changes

2020-04-26 20:58 UTC, EstebenR requested changes
Mejor hacer que las medidas de tiempo vayan con frames en vez de getTime o dependa de que cada frame vaya a 16.66

2020-04-26 20:58 UTC, EstebenR commented on src/config/constants.json
> +  "FRAME_SIZE": 32,
Estos nombres deberían ir tipo CarnivorousPlant_size etc
btw carnivorous no acaba en e

2020-04-26 20:58 UTC, EstebenR commented on src/SourceFiles/CarnivorousPlant.h
> +	float aumento_, actualSpeed_, timePassed_, enterTime_, limitTime_;
aumento deberia ir en ingles

2020-04-27 11:07 UTC, EstebenR approved these changes

2020-04-27 11:34 UTC, jorgmo02 commented on src/SourceFiles/CarnivorousPlant.cpp
> +		int pos = frameSize_ * (frame_ / (int)actualSpeed_) + frameSize_ * idleFrames_;
frame/actualSpeed puede ponerse multiplicando? las divisiones cuestan muchos ciclos

2020-04-27 11:44 UTC, eljorgemo approved these changes
Okey. Hay que revisar los tamaños de los colliders

2020-04-27 15:13 UTC, merged