La caldera baila y echa humo
Tai1Games/Programa-de-Convivencia-Espacial pull request #113
Opened 2020-04-26 19:37 UTC by mmur07

**Cambios en clases existentes:**
-FireballGenerator: Ahora la caldera vibra y expulsa humo. La frecuencia de creación de humo y de la vibración aumentan o disminuyen al pulsar los botones. 

-ParticleEmitter: Ahora soporta spritesheets y cambiar las probabilidades de spawnear partículas . La constructora la he cambiado para adaptar estos cambios.

-ObjectFactory: Ahora le paso un particleEmitter. Tmb le he puesto todo por constantes.

-Viewer: Para hacer que la caldera vibre le he definido un offset. Este offset se aplica al renderizar los objetos. Se puede cambiar con un simple setter. El efecto de vibración es puramente visual, la caldera no vibra de verdad. ✨Magic✨

**Cambios menores**
-Nuevos sprites, constantes y demases

2020-04-26 20:27 UTC, Adrian-de-Lucas-Gomez approved these changes
Los expertos afirman que centrifuga como una lavadora la pena es que no limpia, solo mata.
Estaria bien que se moviese mas de base para que no parezca que se teletransporta pero por todo lo demás guay.

2020-04-26 20:56 UTC, EstebenR requested changes

2020-04-26 20:56 UTC, EstebenR commented on src/SourceFiles/WiFightGameMode.cpp
> +	Entity* lacalderilla = ObjectFactory::makeBoiler(state_->getEntityManager(),state_->getPhysicsWorld(),b2Vec2(5,5));
Me acabo de dar cuenta de que esta linea sobra xd

2020-04-26 20:56 UTC, EstebenR commented on src/SourceFiles/ParticleEmitter.h
> +	int numTextures_;
mmm este nombre necesita mas claridad de que es xd parece como si tuviera mas de una Texture* en vez de ser imagenes en la misma Texture

2020-04-26 20:56 UTC, EstebenR commented on src/SourceFiles/ParticleEmitter.cpp
> +			int numTexture = rand() % numTextures_;
rand es costoso, solo hacerlo si numTextures es mayor a 1

2020-04-27 09:47 UTC, JuanmaSalva approved these changes

2020-04-27 11:20 UTC, EstebenR approved these changes

2020-04-27 11:20 UTC, merged