172411012 jardín botanico
Tai1Games/Programa-de-Convivencia-Espacial pull request #123
Opened 2020-05-01 16:20 UTC by AndresRuizB

añadido fondo del jardin/invernadero y  actualizado el del gym

2020-05-01 19:41 UTC, AdriAlvarez00 requested changes
No aparece la opción de elegir el jardín

2020-05-01 19:45 UTC, AdriAlvarez00 approved these changes
Soy tonto xd

2020-05-01 20:30 UTC, EstebenR approved these changes

2020-05-02 18:09 UTC, JuanmaSalva approved these changes

2020-05-02 18:09 UTC, merged