El jugador ya no sigue agarrado a los objetos cuando se suelta el botón de agarre
Tai1Games/Programa-de-Convivencia-Espacial pull request #124
Opened 2020-05-01 18:34 UTC by Pj6595

2020-05-01 19:38 UTC, AdriAlvarez00 approved these changes
Buen fix

2020-05-01 20:29 UTC, EstebenR approved these changes

2020-05-02 11:50 UTC, eljorgemo requested changes
A veces no te puedes agarrar si vas en paralelo a la pared

2020-05-02 12:14 UTC, eljorgemo approved these changes
Better

2020-05-02 12:15 UTC, merged