[Delivers-#172534740] Lobby
Tai1Games/Programa-de-Convivencia-Espacial pull request #125
Opened 2020-05-02 10:19 UTC by AdriAlvarez00

### LOBBY
No esta integrado, ya que no hay estructura en la que integrarlo aun, pero el lobby es capaz de

- Detectar cuando se unen o abandonan los jugadores, y los guarda. Los mandos se unen con la A/X, el teclado se une con W o I y el raton se conecta con click izquierdo y desconecta con click derecho.

- Si un jugador conectado pulsa su tecla de avanzar (ver ampliacion InputBinder) pasa a estar listo, y con la tecla de back puede ir hacia atras o desconectarse

### AMPLIACION INPUTBINDER
Se han añadido metodos de movimiento en menus en la clase InputBinder, en el futuro habra que dejar de pedir informacion en los menus a inputHandler y pedirla a partir de binder

2020-05-02 22:10 UTC, WillMDev requested changes
-Entiendo que al seleccionar mouse el jugador 1, quitar al jugador 2 si tiene teclado es intencionado. Entonces este estado seria no deseado no?
![unknown](https://user-images.githubusercontent.com/43720307/80893307-7f4c9400-8cd1-11ea-81db-9646067eda64.png)

Para reproducirlo: **W -> I -> Q -> clickIzq**

-También me salta la ventana de error Debug Assertion Failed
Para reproducirlo: **W -> clickIzq -> Q -> clickDerch**

2020-05-02 22:10 UTC, WillMDev commented on src/SourceFiles/InputBinder.h
> +	virtual void setPlayerCol(Collider* col) {};
No debería ser
virtual void setPlayerCol(Collider* col) = 0;
si InputBinder es abstracta pura?

2020-05-03 09:13 UTC, AdriAlvarez00 commented on src/SourceFiles/InputBinder.h
> +	virtual void setPlayerCol(Collider* col) {};
Es intencionado que eche a PureKeyboard2 cuando conectas teclado porque sería bastante incómodo.
SetPlayerCol no es =0 porque por defecto no hace nada, por ahora solo tiene utilizad en el MouseKeyboardBinder ya que hay que sacar la dirección entre su centro y el sitio al que hace click
La excepción es, efectivamente, una exccepción que se nos habia pasado ytenemos que arreglar

2020-05-03 14:14 UTC, JuanmaSalva approved these changes

2020-05-03 15:01 UTC, EstebenR reviewed
me gustaria que aunque aun no este implementado el wrapper, cuando todos hayan aceptado se pueda ir al menú para facilitar la prueba de otras ramas

2020-05-03 15:16 UTC, WillMDev approved these changes

2020-05-03 16:53 UTC, Auraum approved these changes

2020-05-03 16:54 UTC, EstebenR requested changes
me gustaria que aunque aun no este implementado el wrapper, cuando todos hayan aceptado se pueda ir al menú para facilitar la prueba de otras ramas

2020-05-03 19:57 UTC, EstebenR approved these changes

2020-05-03 19:58 UTC, merged