171293107 platano pistola
Tai1Games/Programa-de-Convivencia-Espacial pull request #126
Opened 2020-05-02 18:05 UTC by JuanmaSalva

Ya han PLATANO PISTOLA
**Como funciona:**
-Hay una piscina de plátanos en playState, para poder acceder desde cualquier modo de juego, la piscina de tomates esta en el modo capitalismo pero creo que también debería ir aquí.
-Cuando disparas realmente suelta DOS balas, una es la bala como tal y la otra es una bala en dirección inversa y daño 0 con la textura de la cascara. No se podía usar una partícula por que esta se eliminaba al desactivar el plátano como tal (no la bala)

**Cambios Realizados**
-Creado bananaWeapon y bananaPool (muy similar q los tomates)
-Creado buletBool/bullet, este se puede usar para todo tipo de balas (grapas mas adelante, cofh cofh)
-Dos nuevos métodos en objectFacotry (banana, bullet)
-El metodo para cambiar la textura no funcionaba bien, he hecho los cambios para q funcione
-Añadido sprites Provisionales para el plátano, cascara, y plátano sin piel
-Editado el png de las manos

**Cambios Pendientes**
-Ahora todas las balas son iguales de tamaño pero está hecho de tal manera que se puede editar el tamaño solo que nuestra arquitectura ahora mismo no soporta cambio de tamaños. Cuando esto este se puede hacer que cambien de tamaño.

Creo que no me olvido nada, quiero morir, me voy a por un bocata de nocilla. Feliz Navidad.

2020-05-03 09:08 UTC, AdriAlvarez00 approved these changes
Me gustan los assets decscriptivos

2020-05-03 14:59 UTC, EstebenR requested changes
El platano disparado si toca una pared deberia desaparecer

En el modo por tiempo cuando matas con el platano no te suma la muerte, debería hacerlo

2020-05-03 19:03 UTC, Adrian-de-Lucas-Gomez approved these changes
Esta guay, sobretodo cuando apuntas. Cuando se pueda se hacen los sprites buenos.

2020-05-05 17:34 UTC, EstebenR approved these changes

2020-05-05 17:34 UTC, merged