172534313 avance de la historia
Tai1Games/Programa-de-Convivencia-Espacial pull request #127
Opened 2020-05-03 22:12 UTC by Adrian-de-Lucas-Gomez

Añadido la escena entre partidas en la que vemos como avanzan las rondas y como van quedando los jugadores. La nueva escena se llama MidGame y se puede acceder a ella pulsando el Select en tu mando estando en uno de los mapas.

Esta preparado para distinto número de jugadores, adaptando su colocación en pantalla y también para diferente número de rondas. Para indicar cuantas partidas ha ganado un jugador se sabe por cuanto ha avanzado por la pantalla.

La escena comienza con los cohetes parados y avanza el que ha ganado la última ronda. Tras esto aparece el pantalla el botón de continuar y se hace una transición tope guapa y se pasaría al siguiente mapa (El que decide la clase superior que controla las partidas).

Hay parámetros que de momento están puestos a pelo pero estos nos los dará la clase superior. Al meterte una segunda vez al estado verás que los cohetes están en otra posición pero esto es normal ya que simula que se han actualizado las puntuaciones.

No se asusten si nada mas entrar al estado le dais al botón a pasará directamente a la animación para salir del estado (para pasarlo rápido como dijo Kleon).

2020-05-03 23:06 UTC, EstebenR requested changes
molto bonito, but

Si viewer tiene un componente nFrames_ animatedViewer no debería redefinir otro con el mismo nombre y menos luego en el init cambiar el primero. ¿Por que existen dos?

El texto dice pulsa A para continuar, intuyendo que es la A del mando no tiene soporte para otros controles, igual mejor poner impulso o atacar o agarrar o lo que sea que sea mas universal (Resources.cpp linea 123)

el nido de else if en MidGameState.cpp quedarian mas limpios con un switch

2020-05-04 09:58 UTC, EstebenR requested changes
El codigo sigue pidiendo que le des a la A, no al impulso xd

2020-05-04 11:39 UTC, EstebenR approved these changes
Good save

2020-05-05 13:58 UTC, jorgmo02 commented on src/SourceFiles/MidGameState.h
> +	~MidGameState();
```suggestion
	virtual ~MidGameState();
```

2020-05-05 14:00 UTC, eljorgemo approved these changes

2020-05-05 15:00 UTC, JuanmaSalva approved these changes
to wapa la animacion

2020-05-05 15:00 UTC, merged