Puntos entre partidas
Tai1Games/Programa-de-Convivencia-Espacial pull request #139
Opened 2020-05-09 15:44 UTC by AdriAlvarez00

### CAMBIOS
**Creada la clase MatchInfo**

- Lleva la informacion de los jugadores que se unen en el looby (ID,Puntos,Skin,InputBinder...)
- Vector de pares modo/mapa de las rondas
- Contador de ronda actual y total de rondas
- Aunque no se usa todavia, guarda cuantas victorias por modo de juego tienes.

**Cambios al menu**
- Por defecto, manda el jugador 0 (primero en unirse)
- Funciona con binders menuMove(Dir), menuForward()...
- Ahora mismo te deja elegir tres (3) rondas eligiendo modo y mapa
- Ya no pide jugadores porque se construyen a partir de MatchInfo

**Cambios a midGameState**

- Pide el numero de jugadores y sus ultimas puntuaciones a MatchInfo
- Ahora no hace falta borrarlo después de haber sido creado por primera vez
- Al acabar la partida te devuelve al menú

**Cambios a los gameModes y gameStates**
- Se han hecho varios cambios para facilitar la compatibildad con matchInfo
- Ya no usa la Entidad del winner, solo su id y habla con MatchInfo
- Añadido *BOTON SUPER SECRETO PARA CONTROLLER MASTER RACE* que te gana la ronda automaticamente 

**Cambios a gameStateMachine**
- Ya no hace falta pasar a loadState ni numero de jugadores, ni modo, ni tilemap (MatchInfo)
- Se ha movido onLoaded y se ha quitado el resetState

2020-05-09 16:00 UTC, JuanmaSalva requested changes
Cuando ya has hecho la primera ronda de partidas (cuando vuelves al menu pera volver a elegir) se queda en un bucle infinito de elección de mapas

2020-05-09 16:25 UTC, JuanmaSalva approved these changes

2020-05-09 21:10 UTC, jorgmo02 commented on src/SourceFiles/WiFightGameMode.cpp
> +			winnerId_ = players_[player]->getComponent<PlayerData>(ComponentType::PlayerData)->getPlayerNumber();
Sustituid esto por
```suggestion
			winnerId_ = GETCMP2(players_[player], PlayerData)->getPlayerNumber();
```

2020-05-09 23:29 UTC, jorgmo02 commented on src/SourceFiles/CapitalismGameMode.h
> +	virtual bool onPlayerDead(int id) { return true; }; //Returns false when players runs out of stocks.
```suggestion
```

2020-05-10 00:45 UTC, eljorgemo requested changes
ME HE HARTADO DE MIRAR CÓDIGO, COMPILA PUES EA YA ESTÁ

2020-05-10 08:56 UTC, eljorgemo approved these changes

2020-05-10 14:28 UTC, Adrian-de-Lucas-Gomez requested changes
Al acabar una partida completa de 3 rondas y querer jugar otra todo va bien a excepción de los puntos de los jugadores que no se resetean y en el MidGamestate se van a la puta los cohetes. También pasa si te sales en medio de la partida. Por lo demás está chulisimo y se nota que ha sido un currazo.

2020-05-10 15:33 UTC, Adrian-de-Lucas-Gomez approved these changes
Ya esta todo chachi :D

2020-05-10 15:35 UTC, merged