El router emite "ondas" hacia los jugadores
Tai1Games/Programa-de-Convivencia-Espacial pull request #140
Opened 2020-05-09 16:26 UTC by jorgmo02

En realidad las ondas son balas lol.
Hay que ponerles el sprite de la animación (el sprite actual es provisional), pero por lo demás ya debería estar.
Para accomplishear esta task he hecho una pool que hereda de la de balas y redefine algunas cosas, y he creado un componente que hereda de bala y representa una onda de wifi.
Lo ideal habría sido hacerlo al revés, que la bala heredase de "cosa que va en línea recta y no hace daño", pero como no vamos a usarlo mucho he pensado que no merecía la pena (aplicando filosofía de Esteban).

2020-05-09 16:26 UTC, EstebenR requested changes
baia mierda de sprite loco 0 esfuerzo

2020-05-10 10:25 UTC, JuanmaSalva approved these changes
funcionar funciona bien, pero, asi como esta queda un poco cutre, se que los sprites son provisionales y habria que cambiarlos. Ademas yo he estado jugando con las constantes y queda mucho mejor si le metes mucha velocidad y mas ritmo de generación de partículas. Se puede aprobar pero estaría guapo que estuviera mas perfilado para hacer el merge.

2020-05-10 14:40 UTC, Adrian-de-Lucas-Gomez approved these changes
Esta guay pero queda pendiente de un sprite personalizado y como dice Juanma toquetear las constantes.
Por lo demás todo genial.

2020-05-10 17:52 UTC, EstebenR approved these changes
lo que los demás han comentado

2020-05-10 20:29 UTC, jorgmo02 commented
Me he encontrado con un fallo gordo, en cuanto lo arregle reabro el pull

2020-05-10 20:40 UTC, merged