#172640081 BugFix: No funciona el casting dinámico de Weapon a otras clases que heredan de ella
Tai1Games/Programa-de-Convivencia-Espacial pull request #147
Opened 2020-05-12 19:31 UTC by Will7461

Ahora los componentes de armas se dividen en dos grupos, las que necesitan estrictamente el ComponentTypeId del hijo, y las que no (que ahora llevan ComponentTypeId::Weapon).
Motivo: poder generalizar el trato de las armas, en este caso en Health se buscaba el componente Weapon (desde su ID de Componente) para que las armas que chocan con el jugador apliquen su respectivo ImpactDamage.
Por ahora las siguientes armas tienen ComponentTypeId::Weapon y se pueden usar como en el ejemplo de Health:
Slipper *
Ball *
Stapler *
Extinguisher *
Controller *
Dumbell *
Fireball *
Y las siguientes tienen el ComponentTypeId del hijo (gracias a esto se evitan algunos dynamic_cast):
Confetti
Tomato
Banana
Obviamente estas últimas no aplicaran ImpactDamage.

2020-05-13 09:11 UTC, AdriAlvarez00 requested changes
No me deja editar pq no has tocado esos archivos, pero creo que seria mejor usar Weapon como ID de todas y usar static cast porque las unicas clases que piden Banana,Tomato o Confetti son sus gestores.
Por ejemplo en BananaPool cambiariamos
`e->getComponent<BananaWeapon>(ComponentType::Banana)->setActive(false);`
por 
`BananaWeapon* banana = static_cast<BananaWeapon*>(e->getComponent<Weapon>(ComponentType::Weapon));`

2020-05-13 14:37 UTC, AdriAlvarez00 approved these changes
ahhhh claro el getcomponent ya hace el caseto

2020-05-14 09:07 UTC, JuanmaSalva approved these changes

2020-05-14 09:15 UTC, eljorgemo submitted a review, later dismissed
On hold hasta aclarar lo del daño de las armas

2020-05-14 10:19 UTC, eljorgemo requested changes
@Will7461 te falta quitar los nombres del struct de Components y ya

2020-05-14 20:08 UTC, eljorgemo approved these changes

2020-05-14 20:13 UTC, merged