Las armas ya no se pueden tirar por fuera del mapa
Tai1Games/Programa-de-Convivencia-Espacial pull request #150
Opened 2020-05-14 01:46 UTC by jorgmo02

Basically, lo que he hecho ha sido lo siguiente:
- Cuando un jugador lanza un arma, este arma pone sus capas de colisión a todo lo que tiene normalmente _excepto el jugador que la ha lanzado_. Entonces, los dos objetos se pueden superponer pero colisionan con lo demás de forma correcta.
- El jugador lanza el arma desde su centro (he puesto el ARM_LENGTH a 0.0), porque si sabemos que el jugador no puede salir del escenario, también sabemos que su arma tampoco puede si sale desde el mismo sitio, porque colisionará con la pared.
- He creado capas exclusivas para cada jugador. No hace falta que toquéis nada ni hagáis nada en especial, se puede seguir comprobando con la capa Player (que ahora es la suma de las capas de los otros 4 jugadores).

Os pido que testeéis esto bastante porque si se me ha escapado algo de las capas puede ser una liada (aunque he hecho muchas (muchas(muchas)) pruebas y creo que está bien finalmente).
Not gonna lie, después de hacer esto me siento un poco un maestro de las capas de colisión.

2020-05-14 09:21 UTC, EstebenR requested changes
Las armas a melee no hacen daño

2020-05-14 10:11 UTC, EstebenR approved these changes

2020-05-15 08:22 UTC, JuanmaSalva approved these changes

2020-05-15 15:51 UTC, AdriAlvarez00 approved these changes
Cremoso pull

2020-05-15 15:53 UTC, merged