172599851 Sprites modificados y desarmar al jugador
Tai1Games/Programa-de-Convivencia-Espacial pull request #151
Opened 2020-05-14 10:20 UTC by Adrian-de-Lucas-Gomez

Ahora al recibir un impacto de un objeto lanzable te podrá desarmar. Para ello debe superar una cierta velocidad para evitar que te pueda desarmar un objeto que estuviera flotando. Esa velocidad mínima está asociada a una constante.

También se modificaron los sprites del plátano para que estuviera mas en linea con el resto de las armas y también el color del router para mejorar su visibilidad en la sala de estar y la caldera (Los mapas mas oscuros).

2020-05-14 11:34 UTC, jorgmo02 commented on src/SourceFiles/Health.cpp
> +			//¿Es un objeto lanzable? (Por lo tanto puede desarmar)
En realidad, el que tenga el componente ThrownByPlayer no te garantiza que sea un arma. Lo que sí te lo garantiza es que sea una Weapon, si no me equivoco (de ahí la importancia del static_cast que ha hecho will)

2020-05-15 08:25 UTC, EstebenR approved these changes

2020-05-15 08:27 UTC, JuanmaSalva requested changes
esto no es un cambio, me he equivocado

2020-05-15 08:39 UTC, JuanmaSalva approved these changes

2020-05-15 16:07 UTC, AdriAlvarez00 requested changes
Solo funciona con Health, no con Wallet.
Tambien estaría bien que se usase un metodo que deje el arma quieta, no que la tire

2020-05-15 19:09 UTC, AdriAlvarez00 approved these changes

2020-05-15 19:09 UTC, merged