172751812 añadir objetos por el mapa
Tai1Games/Programa-de-Convivencia-Espacial pull request #152
Opened 2020-05-14 23:59 UTC by Will7461

Ya se pueden añadir objetos a los que te puedes agarrar via Tilemap:
-Sofa
-Mesa
-Lampara

Que pasen buena noche.

2020-05-15 08:32 UTC, JuanmaSalva requested changes
Los objetos no se deberian mover por el mapa. Y las constructoras podrian ser todas una que solo varie el sprite. A la constructora se le pasa el enum de la textura y ya. Para eso usaría la constructora de Wall y añadirle un nuevo parámetro de la textura

2020-05-15 13:40 UTC, mmur07 approved these changes
Muy nice

2020-05-16 11:33 UTC, JuanmaSalva approved these changes

2020-05-16 12:24 UTC, AndresRuizB approved these changes

2020-05-16 12:25 UTC, merged