172534806 transform
Tai1Games/Programa-de-Convivencia-Espacial pull request #156
Opened 2020-05-16 11:05 UTC by AndresRuizB

### **IMPORTANTE: TODAS LAS MEDIDAS DEL TRANSFORM SON EN PIXELES (TAMAÑOS Y OFFSETS) Y ESTOS ÚLTIMOS USAN EL SISTEMA CARTESIANO DEL VIEWER**

Ya se puede cambiar el tamaño de los sprites sin afectar a las fisicas!

Para modificar el sprite, hay que localizar donde se construye el objeto (recomiendo usar cntrl+F y una constante que sepas que tiene) y en su transform modificar el SDL_Rect{x,y,w,h}, de tal forma que:

- **x** es el offset en el eje x
- **y** es el offset en el eje y
- **w** es el tamaño en el eje x
- **h** es el tamaño en el eje y

Por convenio los objetos circulares tienen RADIUS (como constante), por lo que lo usaremos tanto en **w** como en **h**.

Por defecto (**x** = **y** = 0) los sprites se veran con su centro alineado al del collider que corresponden.

El eje X del offset crece hacia la derecha y el eje Y hacia abajo (como los del **Viewer**).

2020-05-16 14:52 UTC, AdriAlvarez00 requested changes
Hay algunas escalas rotas
- Las tuberias son mucho mas pequeñas que su collider
- Los cadaveres son tan grandes como la gloria de tinky
- La cinta de correr está achatada

2020-05-18 12:14 UTC, AndresRuizB commented
> 
> 
> Hay algunas escalas rotas
> 
>     * Las tuberias son mucho mas pequeñas que su collider
> 
>     * Los cadaveres son tan grandes como la gloria de tinky
> 
>     * La cinta de correr está achatada

las dimensiones son temporales, un poco a ojo y tal, cuando lo acepteis lo hago, que es otra historia

2020-05-18 13:06 UTC, EstebenR approved these changes
Echaba de menos los jugadores proporcionados

honestly, I cried

2020-05-18 15:35 UTC, JuanmaSalva approved these changes

2020-05-18 15:44 UTC, AdriAlvarez00 approved these changes
Bueno venga vale

2020-05-18 15:44 UTC, merged

2020-05-18 15:46 UTC, eljorgemo approved these changes