Los objetos no hacen daño
Tai1Games/Programa-de-Convivencia-Espacial pull request #157
Opened 2020-05-16 11:29 UTC by JuanmaSalva

Las armas al lanzarlas ya hacen daño.
Se ha añadido una variable impactForce a weapon y cada arma tiene su constante. Esta variable se multiplica luego por la velocidad del cuerpo para tener la fuerza final con la que se trabaja

2020-05-16 12:09 UTC, AndresRuizB approved these changes

2020-05-16 13:39 UTC, EstebenR requested changes
A poco que roces a alguien con tu propio cuerpo lo matas

2020-05-17 16:15 UTC, EstebenR approved these changes

2020-05-17 16:22 UTC, AndresRuizB approved these changes

2020-05-17 19:15 UTC, WillMDev approved these changes

2020-05-17 19:15 UTC, merged