BugFix: Impulsarse contra tu agarre
Tai1Games/Programa-de-Convivencia-Espacial pull request #161
Opened 2020-05-16 17:05 UTC by AdriAlvarez00

Se comprueba el angulo para ver que te impulsas desde, y no contra.

2020-05-16 18:20 UTC, Adrian-de-Lucas-Gomez approved these changes
Que guay. Esto va a solucionar muchas cosas.

2020-05-16 21:19 UTC, WillMDev requested changes
Funciona con los muebles pero pasa lo contrario con los tinky muertos

2020-05-17 13:10 UTC, EstebenR requested changes
Ahora si estas agarrado a un cuerpo solo te deja impulsarte hacia el

2020-05-18 13:19 UTC, EstebenR requested changes
for some reason la banana esta en el objectFactory

te mete demasiado en las paredes al agarrarte

2020-05-18 14:07 UTC, EstebenR commented on src/SourceFiles/ObjectFactory.cpp
>  	Collider* collRoomba = e->addComponent<Collider>(physicsWorld, b2_staticBody, pos.x, pos.y, CONST(double, "BOILER_WIDTH"), CONST(double, "BOILER_HEIGHT"), CONST(double, "BOILER_DENSITY"), CONST(doub
por que el collider del boiler se llama collRoomba? me acabo de dar cuenta xd

2020-05-18 14:33 UTC, EstebenR approved these changes
ahora si chavales

2020-05-18 16:27 UTC, WillMDev requested changes
El impulso vuelve a ser spameable.

2020-05-19 10:12 UTC, WillMDev approved these changes

2020-05-19 10:13 UTC, merged