Respawn de armas y cambios en la generacion
Tai1Games/Programa-de-Convivencia-Espacial pull request #164
Opened 2020-05-17 18:07 UTC by mmur07

Ahora hay 3 tiers de armas:
 -Low Tier: Confetti y Grapadora. Ambas respawnean tras ser usadas.
 -Mid Tier: Pelota saltarina y mancuerna.
 -High Tier: Extintor y chancla.

Para que veais bien los cambios he cambiado el posicionamiento de las armas en todos los mapas.

**Nuevas clases:**
 -WeaponRespawner: Permite el respawneo del confetti y de la grapadora. Self explanatory.
 -StaplerPool: El stapler no funcionaba por pools asi que he creado una pool para que los maneje.
 -TimedDespawn: Un componente que se lo enganchas a una entidad que lleve un arma y tras ser activado le dice al arma que despawnee. Tiene asignado un respawner para que le diga que respawnee el arma. He hecho que las armas sean lo mas independientes de esto posible para poder crear armas sin necesidad de respawners si sale la ocasión.

**Clases modificadas:**
 -WeaponFactory: Creados metodos para generar weapons aleatorias de un tier en concreto.
 -Tilemap: Ya no decide que weapon exacta se genera. Simplemente llama a WeaponFactory para que le de una weapon aleatoria de un tier en concreto.
 -Weapon: Tiene un método virtual vacio setActive(). El confetti y la grapadora lo usan para manejar el respawneo. Necesitaba que fuera virtual de weapon para usarlo de forma genérica desde el weaponRespawner.
 -Todos los mapas: Ahora usan 3 capas de objetos (tiers) para generar las armas. He cambiado la disposicion de las armas para darle un poco mas de vidilla.
 -ConfettiWeapon y StaplerWeapon: Para que usen TimedDespawn.

2020-05-17 21:38 UTC, eljorgemo requested changes

2020-05-17 21:38 UTC, jorgmo02 commented on src/SourceFiles/ComponentType.h
> +		StaplerWeapon,
en teoría sólo debería haber un tipo de Weapon para que funcione correctamente el GETCMP

2020-05-17 21:38 UTC, jorgmo02 commented on src/SourceFiles/PlayerFactory.cpp
> +	Collider::CollisionLayer layer = Collider::CollisionLayer::Player; /*(Collider::CollisionLayer)(Collider::CollisionLayer::Player1 * pow(2, playerID));*/
Si haces esto te cargas lo de que no se puedan tirar armas por fuera del mapa porque todos los jugadores aparecen en la misma capa

2020-05-17 21:38 UTC, jorgmo02 commented on src/SourceFiles/StaplerWeapon.cpp
> +	viewer_ = GETCMP1_(Viewer);
Nota para el futuro: hacerlo AnimatedViewer para que puedas "cerrar" la grapadora y que se note qué estás disparando

2020-05-18 15:39 UTC, JuanmaSalva commented on src/SourceFiles/ComponentType.h
> +		StaplerWeapon,
bro jorge revisa su cambio

2020-05-18 15:39 UTC, eljorgemo approved these changes

2020-05-18 15:53 UTC, JuanmaSalva approved these changes

2020-05-18 16:07 UTC, Adrian-de-Lucas-Gomez approved these changes
Está chachi

2020-05-18 16:31 UTC, JuanmaSalva reviewed
Tiene conflictos esta movida :(

2020-05-19 08:14 UTC, merged