Añadidos sonidos a los menus
Tai1Games/Programa-de-Convivencia-Espacial pull request #174
Opened 2020-05-19 16:54 UTC by EstebenR

2020-05-20 08:35 UTC, JuanmaSalva approved these changes

2020-05-20 08:36 UTC, JuanmaSalva reviewed
Estaria bien q tmb estuvieran cuando un jugador se une

2020-05-20 09:55 UTC, mmur07 requested changes
Tendrían que sonar un poco más alto imho. No se escuchan con la música.

2020-05-21 10:57 UTC, mmur07 approved these changes

2020-05-21 11:02 UTC, AdriAlvarez00 approved these changes

2020-05-21 11:06 UTC, merged