Sprite y animacion de los botones de la caldera
Tai1Games/Programa-de-Convivencia-Espacial pull request #184
Opened 2020-05-20 10:47 UTC by mmur07

También he cambiado la lógica de los timings porque funcionaba con SDL_Time y no con frames.

2020-05-20 10:56 UTC, Auraum requested changes
Está bien pero haría la animación más rápida. Ahora mismo si le lanzas un objeto relativamente rápido le da tiempo a rebotar antes de que el botón se active.

2020-05-20 12:15 UTC, Adrian-de-Lucas-Gomez approved these changes
Está todo guay. Pon la animación en 2 o 3 que creo que es como mejor queda.

2020-05-20 16:34 UTC, WillMDev approved these changes
Si, yo también haría un poco más rápida la animación para que pegue un poco más luego con el sonido.

2020-05-20 21:14 UTC, EstebenR approved these changes

2020-05-21 09:44 UTC, Auraum approved these changes

2020-05-21 09:44 UTC, merged