Animaciones de Mano (Confetti y Tomate)
Tai1Games/Programa-de-Convivencia-Espacial pull request #202
Opened 2020-05-23 09:33 UTC by mmur07

Ahora se puede animar la mano. También he hecho el confetti y el tomate animados en la mano.

**Cambios importantes**
-Hands: Ahora es un AnimatedViewer. Como no hice ni uno ni el otro igual es un poco spaghetti pero bueno, si veis alguna cosa horrible pedidme cambios.

-ConfettiWeapon: Dependiendo en que estado esté (cargado, disparando, sin municion) le dice a la mano en qué frame de la animación se tiene que poner. Lo podría haber hecho por animación pero siendo 3 frames me parecía más cómodo así.

-TomatoWeapon: Ah yes, welcome to Spaghetti Town 🍝 Ahora está animado cuando está en la mano. En este si que he usado el StartAnimation(). También he arreglado el bug de que al respawnear aparecian explotados y no se podían recoger. También he pasado su lógica a frames en vez de SDLTime.

**Cambios menores:**
-He añadido el nuevo sprite del tomate.
-He modificado el sprite del confetti para que sea más pequeño.
-Cambios en constantes para mejorar el tomate.

2020-05-23 10:07 UTC, JuanmaSalva commented
> Ah yes, welcome to Spaghetti Town 🍝

Que maravilla esta frase

2020-05-23 10:13 UTC, JuanmaSalva requested changes
Cunado activas un tomate y lo lanzas tus manos se desactivan durante un tiempo (como 1 o 2 segundos)

2020-05-23 12:34 UTC, eljorgemo requested changes
El tomate se anima incluso si no lo has activado, creo que tienes que poner StopAnimation() en el tomate

2020-05-23 12:34 UTC, eljorgemo commented on src/SourceFiles/ConfettiWeapon.cpp
> +			if (currentHand_) currentHand_->setFrame(2, weaponType_);
```suggestion
			if (currentHand_ != nullptr) currentHand_->setFrame(2, weaponType_);
```
Os recuerdo que si sólo ponéis el puntero como un booleano estáis comparando otra cosa

2020-05-23 12:34 UTC, eljorgemo commented on src/SourceFiles/ConfettiWeapon.cpp
> +	if (currentHand_) {
lo mismo aquí

2020-05-23 13:21 UTC, EstebenR requested changes
Si coges un tomate y lo tiras sin activarlo se queda loopeando la animacion

Si activas y tiras un tomate y acto seguido coges otro tomate, la animacion sigue en el tomate que tienes en la mano

2020-05-23 21:04 UTC, EstebenR requested changes
El confeti no esta generando collider de ataque (las demas armas a melee si)

2020-05-23 22:07 UTC, EstebenR approved these changes

2020-05-23 22:08 UTC, EstebenR requested changes
gracioso

2020-05-23 22:09 UTC, EstebenR approved these changes

2020-05-23 22:56 UTC, eljorgemo approved these changes

2020-05-23 22:56 UTC, jorgmo02 commented on src/SourceFiles/ConfettiWeapon.cpp
> +	if (currentHand_) {
```suggestion
	if (currentHand_ != nullptr) {
```

2020-05-23 22:56 UTC, jorgmo02 commented on src/SourceFiles/Hands.cpp
> +	double angle = std::atan2((double)stickDir.x, -(double)stickDir.y) * (180.0 / PI) + 90;
el ángulo también cambia en el update, no se puede reutilizar? (pregunto)

2020-05-23 22:56 UTC, jorgmo02 commented on src/SourceFiles/TomatoWeapon.cpp
> +			tomatoViewer_->setFrame(nFramesCharge_);
esta sobra
```suggestion
```

2020-05-23 23:01 UTC, jorgmo02 commented on src/SourceFiles/TomatoWeapon.cpp
> +			tomatoViewer_->setFrame(nFramesCharge_);
esta sobra
```suggestion
```

2020-05-24 15:14 UTC, JuanmaSalva approved these changes

2020-05-24 15:15 UTC, merged