Animación ataque a melé
Tai1Games/Programa-de-Convivencia-Espacial pull request #206
Opened 2020-05-23 12:21 UTC by jorgmo02

Es independiente del número de frames (o sea, se puede hacer que dure más el ataque y la animación dura lo mismo). La he hecho como pedisteis, al estilo Hollow Knight (sólo un frame que completa todo el recorrido)

2020-05-23 22:09 UTC, EstebenR submitted a review, later dismissed
queda pendiente hasta que se acepte la rama base

2020-05-24 16:16 UTC, EstebenR requested changes
Que dure mas la animacion

2020-05-24 22:45 UTC, eljorgemo reviewed
@EstebenR ya dura más la animación (el número de frames va por constante y es independiente de la hitbox)

2020-05-24 22:57 UTC, EstebenR approved these changes

2020-05-25 11:04 UTC, JuanmaSalva requested changes
Si atacas a mele y luego intentas lanzar el arma el juego hace Boom Boom Boom y peta

2020-05-25 11:24 UTC, JuanmaSalva approved these changes

2020-05-25 11:28 UTC, WillMDev approved these changes

2020-05-25 11:29 UTC, merged