Componente Collider
Tai1Games/Programa-de-Convivencia-Espacial pull request #21
Opened 2020-03-01 17:32 UTC by Auraum

[Delivers 171442111] Es posible que necesitemos más métodos más adelante, de momento es una versión simple que hace colliders rectangulares, con un fixture y sin articulaciones.

2020-03-01 18:51 UTC, EstebenR requested changes
Todo bene pero hacer que se incluya en el proyecto

2020-03-01 19:13 UTC, EstebenR approved these changes

2020-03-02 16:29 UTC, AndresRuizB approved these changes

2020-03-02 16:30 UTC, JuanmaSalva approved these changes
ok

2020-03-02 16:30 UTC, merged