Bugfix si te desarman no puedes coger ese arma
Tai1Games/Programa-de-Convivencia-Espacial pull request #216
Opened 2020-05-24 16:54 UTC by jorgmo02

2020-05-24 18:41 UTC, EstebenR approved these changes

2020-05-24 19:49 UTC, mmur07 requested changes
No funciona con el confetti

2020-05-24 21:49 UTC, eljorgemo reviewed
@mmur07 arreglado el bug

2020-05-25 09:26 UTC, mmur07 approved these changes

2020-05-25 10:58 UTC, JuanmaSalva approved these changes

2020-05-25 10:58 UTC, merged