nuevos sprites
Tai1Games/Programa-de-Convivencia-Espacial pull request #224
Opened 2020-05-25 14:23 UTC by JuanmaSalva

nueva animacion de la cama elastica

2020-05-25 15:51 UTC, WillMDev approved these changes

2020-05-25 16:01 UTC, EstebenR requested changes
las colchonetas son demasiado grandes, la incrustaria en la pared para que no queden demasiado estrechas al resizearlas

2020-05-25 16:33 UTC, Adrian-de-Lucas-Gomez approved these changes
El sprite es chulo , con que cambies la posición y estén mas metidas en las paredes lo bordas.

2020-05-26 08:56 UTC, EstebenR approved these changes

2020-05-26 08:56 UTC, merged