Te puedes tirar pedos en español
Tai1Games/Programa-de-Convivencia-Espacial pull request #229
Opened 2020-05-25 17:20 UTC by Auraum

[Delivers #172894049] He puesto el sprite de la espuma de extintor porque es básicamente lo mismo pero se puede cambiar. Todo el texto no provisional debería estar en español. (F por las tildes y eñes)

2020-05-25 17:32 UTC, EstebenR requested changes
Puedes spamear el impulso y aunque no te impulses salen mil peditos

2020-05-25 17:41 UTC, WillMDev requested changes
Faltan los nombres de mapas y modos de juego

2020-05-25 17:43 UTC, WillMDev approved these changes

2020-05-25 17:57 UTC, Auraum commented
> Puedes spamear el impulso y aunque no te impulses salen mil peditos

fixed

2020-05-25 18:16 UTC, EstebenR approved these changes

2020-05-26 08:37 UTC, JuanmaSalva approved these changes

2020-05-26 08:53 UTC, merged