Los daltónicos ya pueden disfrutar del capitalismo
Tai1Games/Programa-de-Convivencia-Espacial pull request #236
Opened 2020-05-25 22:03 UTC by Auraum

2020-05-25 22:56 UTC, EstebenR requested changes
Falta el timed para la cuenta de vidas

2020-05-25 22:57 UTC, EstebenR commented
Y tambien lo de gana X jugador en todos los modos

2020-05-26 00:58 UTC, eljorgemo requested changes
Quita los log

2020-05-26 09:03 UTC, EstebenR approved these changes

2020-05-26 10:46 UTC, Auraum commented
> Quita los log

fixed

2020-05-26 11:33 UTC, eljorgemo approved these changes

2020-05-26 11:57 UTC, JuanmaSalva approved these changes

2020-05-26 11:57 UTC, merged