#171442965 escena prueba
Tai1Games/Programa-de-Convivencia-Espacial pull request #24
Opened 2020-03-03 11:57 UTC by jorgmo02

Importante, probadla y ved que funciona bien

2020-03-03 12:06 UTC, mmur07 submitted a review, later dismissed
Error LNK salu2.

2020-03-03 12:13 UTC, Pj6595 requested changes
Da error de linker porque SDL_Game::start no tiene definición. Si pongo corchetes en start para que tenga un cuerpo (vacío) y que al menos se ejecute el programa, se abre y se cierra sin más y no sale ninguna escena.

2020-03-03 15:06 UTC, Pj6595 approved these changes
Ahora sí.

2020-03-04 11:16 UTC, JuanmaSalva approved these changes
oka

2020-03-04 11:26 UTC, AdriAlvarez00 approved these changes
gg wp

2020-03-04 11:28 UTC, AndresRuizB approved these changes

2020-03-04 11:33 UTC, merged