Esta vez sí
Tai1Games/Programa-de-Convivencia-Espacial pull request #29
Opened 2020-03-04 16:51 UTC by Auraum

Esperemos

2020-03-04 19:40 UTC, EstebenR approved these changes

2020-03-04 19:52 UTC, mmur07 requested changes
Para crear 2 fixtures va bien. Pero al crear la tercera reemplaza a la segunda.

No se si en algún momento necesitaremos 3 fixtures en el mismo body pero mejor mirarlo ahora que más tarde.

2020-03-04 19:53 UTC, Adrian-de-Lucas-Gomez approved these changes

2020-03-04 19:53 UTC, Pj6595 approved these changes
Confío en que el Ministro de Físicas esté haciendo bien su trabajo.

2020-03-04 19:57 UTC, JuanmaSalva approved these changes
sep

2020-03-06 12:05 UTC, mmur07 approved these changes
Teperd0no

2020-03-06 12:05 UTC, merged