Agarrarse a objetos terminado para que Juanma pueda pegarse con lo del impulso
Tai1Games/Programa-de-Convivencia-Espacial pull request #30
Opened 2020-03-04 19:42 UTC by mmur07

Cosas nuevas:

>He creado 1 nueva clase (componente) AttachableObject que se le mete al jugador en cuestión.

------------------------------------------------------
Cosas modificadas:

>He tocado la escena de prueba para que podáis ver el joint en acción.

>He añadido un getter en Collider.h para obtener un b2world y el body del jugador que necesito en AttachableObject para crear el joint. Es la manera menos fea que se me ha ocurrido de hacerlo ya que no quería pasarselo como parámetro en la constuctora. Que Álvar me castigue si lo ve necesario 😞

------------------------------------------------------
Cosas que quedan por hacer:

> Hacer que los objetos a los que te puedas agarrar tengan otro collider sensor un poco más grande que el principal al que te agarras de verdad. Pensadlo como una hitbox.

> Implementar todo esto con el inputHandler.

2020-03-04 19:58 UTC, AdriAlvarez00 approved these changes
Looks good

2020-03-04 20:02 UTC, Pj6595 submitted a review, later dismissed
Espero que Juanma gane la pelea.

2020-03-04 20:03 UTC, EstebenR requested changes
Pendiente de aceptacion hasta que este terminado

2020-03-06 14:20 UTC, mmur07 commented
Cierro el pull request dado que la feature no está terminada dado que necesito que se completen 2 historias: El input handler y que los objetos colisionen.

2020-03-06 14:20 UTC, closed without merging