[delivers - #171442130] Input Handler
Tai1Games/Programa-de-Convivencia-Espacial pull request #32
Opened 2020-03-06 16:53 UTC by AdriAlvarez00

CÓMO DEBUGEAR
- Enchufar un mando Xbox360 o XInput (srry Juanma)
- Descomentar el metodo DebugInput() y lo que se quiera comentar
- Comprobar que detecta pulsaciones, mantener pulsacion y soltar botones
- Comprobar que devuelve la direccion de los sticks
- Devuelve el valor de los triggers

2020-03-06 17:14 UTC, EstebenR requested changes
hacer que se acate al modelo de gameStates nuevo (quitarlo de playstate), el debug se puede quedar en playstate pero meter el handle en el handle de gamestate

2020-03-07 10:47 UTC, JuanmaSalva approved these changes
Bien aun que el lunes nos tienes q dar un corso de usarlo a todos jeje

2020-03-07 14:33 UTC, WillMDev approved these changes
si

2020-03-07 14:54 UTC, EstebenR approved these changes
super de puta madre socio

2020-03-07 14:54 UTC, merged