[delivers - #171442590] Componente Tilemap
Tai1Games/Programa-de-Convivencia-Espacial pull request #37
Opened 2020-03-14 14:24 UTC by AdriAlvarez00

Explicacion en src/Documentation.md
Si queréis verlo bonito que la ventana tenga una aspect ratio multiplo de 32:32

2020-03-14 17:16 UTC, AndresRuizB commented on src/SourceFiles/TileMap.h
> +	SDLTexturesManager* tm;
Barrabaja

2020-03-14 17:38 UTC, AndresRuizB requested changes
pon la barrabaja xd

2020-03-14 21:25 UTC, AndresRuizB approved these changes

2020-03-15 11:39 UTC, EstebenR requested changes
Men borraste el box2d.lib xd

2020-03-15 15:37 UTC, JuanmaSalva approved these changes
Oka

2020-03-15 17:09 UTC, EstebenR commented
Resulta que faltaban las librerias debug y release de box2d

2020-03-15 17:10 UTC, EstebenR requested changes
Las librerias debug y release no pueden ir en carpetas llamadas 'debug' o 'release' porque están en el gitignore poner otro nombre asi sea test y prod

2020-03-16 11:11 UTC, mmur07 approved these changes
Mola un montón 👍

2020-03-16 11:53 UTC, EstebenR approved these changes

2020-03-16 11:59 UTC, AdriAlvarez00 commented
Resueltos los merge conflicts

2020-03-16 12:04 UTC, merged