171234526 damage on impact
Tai1Games/Programa-de-Convivencia-Espacial pull request #39
Opened 2020-03-14 21:08 UTC by Adrian-de-Lucas-Gomez

[Finishes #171234526] Los impactos ya funcionan y se aplican los daños (quedará para la fase de testing los ajustes pertinentes). También se han añadido a Resources las imágenes de algunos de los objetos que ya tenemos.

2020-03-14 21:39 UTC, AndresRuizB commented on src/SourceFiles/CollisionHandler.cpp
> +	if (impact >= 65) {playerHealth->subtractLife(3);}
los limites de daño mejor en constants.h

2020-03-14 21:40 UTC, AndresRuizB requested changes
Lo de mover los limites de daño a constants

2020-03-14 21:47 UTC, Adrian-de-Lucas-Gomez commented on src/SourceFiles/CollisionHandler.cpp
> +	if (impact >= 65) {playerHealth->subtractLife(3);}
Ya está, lo acabo de poner.

2020-03-14 21:48 UTC, AndresRuizB approved these changes
Perf ;D

2020-03-15 10:51 UTC, EstebenR requested changes
La colision no revisa si es un jugador, en la linea 56 del CollisionHandler.cpp el if solo tiene un '=' y no un '==' por tanto no estaba haciendo la comprobación xd.

Hay que:
*Hacer que sí que sea una comparación.
*Añadir el userData al collider pasandole el Entity al que va pegado cuando se crea.
*Hacer una comprobacion pidiendo el componente del user data (GetUserData().GetComponent o el equivalente que esté hecho para pedir el componente de una entidad) mirando si tiene health para poder restarsela

2020-03-15 16:42 UTC, EstebenR approved these changes

2020-03-15 17:51 UTC, AdriAlvarez00 approved these changes
Correcto, pero igual habría que implementar una forma de diferenciar entre objetos duros y blandos

2020-03-15 17:57 UTC, merged