Agarrarse a objetos
Tai1Games/Programa-de-Convivencia-Espacial pull request #40
Opened 2020-03-15 17:12 UTC by mmur07

**Cambios realizados:**
Nuevo componente:
 -AttachesToObjects: Se añade al jugador. Permite que este se agarre a otros objetos.

Cambios en clases:
 -Collider: Cambia su constructora añadiendo un booleano al final que indica si el jugador se puede agarrar a ese objeto. Si es true, crea una nueva fixture de tipo TRIGGER.

-CollisionHandler: Nuevos métodos que verifican y aplican las colisiones entre el jugador y objetos agarrables. 

**Ciclo del joint**
La lógica funciona de este modo: Empieza el step -> Detecta colisión entre jugador y objeto agarrable -> Si el jugador está pulsando la A (mando) y no está agarrado a otro objeto, la valida -> Añade los datos necesarios para crear el joint a un vector (no se puede crear un joint en mitad del step) -> Acaba el step -> Inmediatamente después, resuelve los joints (Método SolveInteractions en CollisionHandler) -> Siguiente step -> ...

**Problemas y posibles cambios**
Pensaba añadir una fixture un poco más grande que el collider original que actuara como hitbox para que el jugador pudiera agarrarse con un poco más de márgen. Esto se hace con sensores para que el jugador rebote con la hitbox pero el problema es que un sensor no puede devolver un punto de colisión al chocar con otra fixture. Esto hace que explote el programa (mover paredes estáticas...) y requeriría una forma bastante distinta de managear las colisiones (recorrer todo el vector de objetos a los que se puede agarrar el jugador en cada step para ver si colisiona con alguno). Como esta historia lleva demasiado tiempo activa y esta implementación puede funcionar, he decidido no ponerle el sensor y dejarlo con el mismo tamaño que el fixture original

2020-03-15 18:25 UTC, AdriAlvarez00 requested changes
Hay conflictos de merge en CollisionHandler. Parece que recibes daño aunque te agarres al chocar con un objeto, mira a ver cómo se integra con el DamageOnCollision

2020-03-16 11:01 UTC, JuanmaSalva approved these changes
Ole ole lo caracole

2020-03-16 11:04 UTC, AdriAlvarez00 approved these changes

2020-03-16 11:52 UTC, AndresRuizB commented on src/SourceFiles/CollisionHandler.cpp
> +		cout << "jaja si" << endl;
jaja no

2020-03-16 11:56 UTC, mmur07 commented on src/SourceFiles/CollisionHandler.cpp
> +		cout << "jaja si" << endl;
@Pj6595 👀

2020-03-16 12:04 UTC, mmur07 commented on src/SourceFiles/CollisionHandler.cpp
> +		cout << "jaja si" << endl;
Ya debería estar en el último commit

2020-03-16 12:07 UTC, Pj6595 approved these changes
jaja si

2020-03-16 12:09 UTC, merged