171820264 error sin mando
Tai1Games/Programa-de-Convivencia-Espacial pull request #44
Opened 2020-03-18 16:18 UTC by JuanmaSalva

[Finishes #171820264]
No peta pero solo reacciona a esas funcionalidades que acepten input de teclado

2020-03-18 17:12 UTC, EstebenR requested changes
En vez de hacer la comprobacion del tamaño siempre que se vaya a pedir el input hacerlo en la clase InputHandler. Cuando se vaya a pedir un boton asegurarse de que no se sale del numero de mandos disponibles.
Sería en los metodos de los botones, los Sticks y los triggers.

Andrés warro

2020-03-18 17:12 UTC, jorgmo02 commented
Y si en lugar de hacer tantas comprobaciones en sitios diferentes, sólo comprobamos en el while(!exit)?
(en SDL_Game::start)

2020-03-20 13:35 UTC, EstebenR approved these changes
Bene, se puede cambiar una vez ya no tengamos el playstate como menu principal pero de momento funciona bien

2020-03-21 17:22 UTC, AdriAlvarez00 requested changes
Hay que cambiar try catch por comprobaciones en los vectores

2020-03-21 17:22 UTC, AdriAlvarez00 commented on src/SourceFiles/SDL_Game.cpp
>  	}
Si no hacemos nada en el catch creo que es mejor preguntar en los métodos de joystick si id < joystick.size()

2020-03-22 11:29 UTC, EstebenR commented on src/SourceFiles/SDL_Game.cpp
>  	}
De acuerdo, sabiendo que no va a dar excepcion incontrolada mejor quitar el trycatch

2020-03-24 09:56 UTC, EstebenR approved these changes

2020-03-24 09:59 UTC, JuanmaSalva commented on src/SourceFiles/SDL_Game.cpp
>  	}
hacerlo al principio quita un huevo y medio de comprobaciones. Si hay que hacerlo en cada método cada vez que hay input se comprueba cuando si desde el principio están todos conectados no fallará

2020-03-24 20:12 UTC, AdriAlvarez00 approved these changes
Bien, pero hay errata en la linea 109 de SDL_Game.cpp

2020-03-25 18:37 UTC, jorgmo02 commented
Seems alright

2020-03-25 18:37 UTC, eljorgemo approved these changes

2020-03-25 18:38 UTC, merged