171315156 pausa
Tai1Games/Programa-de-Convivencia-Espacial pull request #45
Opened 2020-03-19 16:06 UTC by Will7461

-Ahora Viewer soporta texturas sin Collider. (UI elementos)
-Cada vez que se cambie al estado pausa hay que especificar un owner, setPauseOwner(int ownerID), como changeToState() solo sirve para crear el estado si no lo está, he usado un método exterior para pasar a pausa con un owner (setPauseOwner(int ownerID)).
-Para moverse por el menú se usa el stick derecho (avisadme si quereís cambiarlo al izq) y para aceptar, el botón A.

2020-03-19 16:29 UTC, eljorgemo requested changes
Faltan el ángulo y el clip en el Viewer para elementos de la UI (Viewer.cpp, línea 59)

2020-03-21 13:58 UTC, EstebenR requested changes
El control dentro de la pausa sea o con el stick izquierdo o el d-pad
Also si estas en pausa que si le das al botón otra vez se des-pause

2020-03-21 17:26 UTC, AdriAlvarez00 approved these changes
Cuando implementemos salir hay que acordarse de colocarlo aquí, pero todo bien

2020-03-21 17:26 UTC, EstebenR approved these changes
Ta to gucci
Me gusta lo del slider del volumen

2020-03-21 17:39 UTC, jorgmo02 commented
I'm impressed pero sin impresora

2020-03-21 17:40 UTC, eljorgemo approved these changes

2020-03-21 17:40 UTC, merged