171293210 gamelogic
Tai1Games/Programa-de-Convivencia-Espacial pull request #47
Opened 2020-03-21 17:54 UTC by mmur07

**Nuevas clases:**
 -PlayerData: Contiene información que usarán el resto de componentes relacionados con el jugador. SIEMPRE se crea antes que cualquier otro componente del jugador.

-GameMode: Clase abstracta de la que heredan el resto de modos de juego.

-StocksGameMode: Hereda de la clase GameMode. Redefine sus métodos abstractos para adaptarlos.

**Cambios en otras clases:**
-Hemos adaptado HealthViewer para que use constantes.

-PlayState ahora se construye pasándole un GameMode a la que guarda referencia.

2020-03-21 18:15 UTC, EstebenR approved these changes

2020-03-22 12:00 UTC, Pj6595 approved these changes

2020-03-22 13:15 UTC, eljorgemo approved these changes
Está nice. Me gusta que exista la clase PlayerData

2020-03-22 13:15 UTC, merged

2020-03-22 13:19 UTC, AndresRuizB commented on src/SourceFiles/StocksGameMode.h
> +	StocksGameMode(int stocks = 3);
Constants

2020-03-22 13:20 UTC, AndresRuizB requested changes
moved eso a constants pero ta bien