[Finishes #171234764]
Tai1Games/Programa-de-Convivencia-Espacial pull request #50
Opened 2020-03-22 18:13 UTC by Auraum

Terminados respawn, soltar arma y dejar cuerpos muertos. Implementado para funcionar con el stocks game mode. De manera provisional los jugadores respawnean en un sitio arbitrario que depende de su ID y al quedarse sin vidas se teletransportan lejos para no afectar a la partida. También arreglado un fallo que hacía que los jugadores se hicieran daño al chocarse contra los triggers de las armas.

2020-03-22 18:33 UTC, Pj6595 approved these changes
No me puedo mover para probarlo pero lo que he visto parece que está correcto así que amén

2020-03-24 08:59 UTC, AdriAlvarez00 approved these changes
Va a haber que refactorizar más adelante pero we

2020-03-24 08:59 UTC, AdriAlvarez00 commented on src/SourceFiles/CollisionHandler.cpp
> +		StocksGameMode* s = static_cast<StocksGameMode*>(gMode_);
Esto tiene que ser para cualquier gameMode, no solo para stocks porque hay que informar al juego de que un jugador ha muerto

2020-03-24 10:01 UTC, EstebenR requested changes
Waiting on el merge de lo de juanma

2020-03-25 19:48 UTC, EstebenR approved these changes
ole ole lo caracole

2020-03-25 19:48 UTC, merged