[Finishes #171293123] chancla
Tai1Games/Programa-de-Convivencia-Espacial pull request #52
Opened 2020-03-23 18:57 UTC by Adrian-de-Lucas-Gomez

Ya está hecho y funcional. Cuando cojas la chancla se desactiva la colisión de la misma y se activa el trigger que al entrar en contacto con los otros jugadores les aplica el daño correspondiente.

2020-03-24 09:28 UTC, AdriAlvarez00 approved these changes
No pises a tinky, que lleva cholas

2020-03-27 10:53 UTC, EstebenR requested changes
¿Por que se ha borrado lo de llamar a action en Weapon.cpp?

Also mergear el master pls

2020-03-27 18:00 UTC, Adrian-de-Lucas-Gomez commented
> 
> 
> ¿Por que se ha borrado lo de llamar a action en Weapon.cpp?
> 
> Also mergear el master pls

Ya está. No se llama a Action ya al pulsar el botón ya que el modo de ataque de la chancla se pone nada mas cogerla por lo que Action ya unicamente calcula el daño de debe de hacer el jugador al golpear.

2020-03-29 16:12 UTC, EstebenR approved these changes
Bene

2020-03-29 19:36 UTC, mmur07 requested changes
La chancla tiene que hacer knockback

2020-03-29 22:39 UTC, mmur07 commented
> 
> 
> La chancla tiene que hacer knockback

Okay, queda bien con el knockback alto. Igual quedaría menos wonky si la dirección del impulso fuera desde el jugador que tiene la chancla hacia el enemigo en vez de partir desde la chancla hacia el enemigo. También habría que especificar exactamente cómo queremos que funcionen las armas (si con el swing tuyo o con animación fija). La culpa recae en mi que tampoco lo especificamos en el GDD asi que sorry por mi parte. Ya si eso lo podemos comentar mañana en el scr00m 👌

2020-04-03 15:57 UTC, EstebenR requested changes
Si ataco con la chancla y acto seguido la tiro salta excepcion

2020-04-04 19:12 UTC, EstebenR approved these changes
ya furula

2020-04-05 09:44 UTC, mmur07 approved these changes
te perd0no !1

2020-04-05 09:44 UTC, merged