[delivers-#171901299] Carga de constantes por JSON
Tai1Games/Programa-de-Convivencia-Espacial pull request #53
Opened 2020-03-25 17:26 UTC by AdriAlvarez00

### Ya no hace falta recompilar el proyecto cada vez que se toque una constante.

en src/config/constants.json se añade un par nuevo al json y para usarlo se usa el macro CONST(tipo de la variable,string con el nombre de la variable).
**Cuidado de no liarla porque da excepción. Y cuidado con los espacios donde no tocan**

2020-03-26 20:27 UTC, WillMDev requested changes
Estaría bien agregar algún tipo de separación en el archivo json porque más adelante va a terminar siendo un caos de constantes juntas. [https://stackoverflow.com/questions/244777/can-comments-be-used-in-json](url) Aquí dan algunas ideas aunque a las malas supongo que con espacios en blanco nos valdría.

2020-03-27 10:49 UTC, EstebenR approved these changes

2020-03-27 11:17 UTC, WillMDev approved these changes

2020-03-27 16:34 UTC, Auraum approved these changes

2020-03-27 16:34 UTC, merged