Creado el modo de juego 'Pelea por el mando'
Tai1Games/Programa-de-Convivencia-Espacial pull request #54
Opened 2020-03-25 19:05 UTC by Pj6595

La gracia del modo de juego sería que un jugador muriera y droppeara el mando, pero como la cosa de Álvar no está aceptada pues cuando lo esté tendrá gracia.

La UI es una cosa para probar (porque eso es otra historia de Pivotal) así que no nos hagáis bullying por ello.

2020-03-25 19:07 UTC, Auraum approved these changes
Impresionante trabajo

2020-03-26 09:15 UTC, AdriAlvarez00 submitted a review, later dismissed
No hace falta Entity* winner. Sacad el ganador de roundResults_ en GameMode porque va a ser algo que usen todos los modos

2020-03-29 09:39 UTC, EstebenR requested changes
Mergead el master para hacer el cambio de las constantes

2020-03-29 16:17 UTC, EstebenR submitted a review, later dismissed
No compila por las constantes genios

2020-03-29 22:14 UTC, mmur07 approved these changes
Me gusta que el mando mate a jugadores sin ningún tipo de esfuerzo.

2020-03-30 08:36 UTC, AdriAlvarez00 approved these changes
Cada vez es más necesaria la historia de balanceo

2020-03-31 13:25 UTC, EstebenR submitted a review, later dismissed
on hold

2020-03-31 13:27 UTC, merged