171293217 wi fight - Leed descripcion
Tai1Games/Programa-de-Convivencia-Espacial pull request #56
Opened 2020-03-29 18:51 UTC by mmur07

Terminado el modo de juego Wi-fight

**Nuevas clases**
- WiFightGameMode: Nuevo gamemode que genera una entidad Router. La puntuación de cada jugador se guarda en un vector de doubles playerProgress_.
El router está compuesto por una fixture que solo rebota con las paredes y otra sensor que detecta jugadores.

-RouterLogic: Cuando un jugador entra en el área de su fixture sensor, lo registra en un vector. Cuando el jugador sale del área, lo expulsa del vector. En cada ciclo del update suma puntos a cada jugador en el área dependiendo de lo lejos que estén y del número de jugadores en el área. Un jugador gana cuando llega a 100 puntos.

**Cambios en otras clases**
- Collider: Creada la capa uninteractableObject y arreglado el horror de las colisiones entre capas. Ahora ya no hay un método CreateFixture. Hay un método CreateRectangularFixture y otro CreateCircularFixture. Necesitaba el segundo para crear el sensor del router.

- GameMode: En vez de tener un vector roundResults de Entidades jugador, ahora solo se registra 1 único jugador en la variable Winner. Para adaptar estos cambios he modificado la clase StocksGameMode.

- CollisionHandler: Comprueba colisiones entre el router y los jugadores.

2020-03-29 20:15 UTC, Pj6595 requested changes
No puedo probarlo porque en ningún sitio se dice al jugador su progreso y no se sabe si está funcionando bien. Comentadlo por consola aunque sea plz

2020-03-29 20:24 UTC, Pj6595 approved these changes
Va bien, me gusta el sistema de ganar más puntos cuanto más te acercas.

2020-03-29 21:49 UTC, EstebenR approved these changes

2020-03-29 21:51 UTC, EstebenR reviewed
Sale constantemente que el jugador ha ganado aunque no llegue a cien puntos?

2020-03-29 21:57 UTC, mmur07 commented
> 
> 
> Sale constantemente que el jugador ha ganado aunque no llegue a cien puntos?

No se si es a lo que te refieres pero cuando el primer jugador llega a 100 el booleando roundFinished se pasa a true. 
Ahora mismo no hacemos nada con ese booleano y se siguen sumando puntos todo el rato y por eso sale en consola que "ganan" todos los jugadores. En un futuro cuando ese booleano se vuelva true te sacará del modo de juego así que no problemo. Igual debería parar el update del router si roundFinished es true tho.

2020-03-31 08:22 UTC, AdriAlvarez00 approved these changes
Muy guay, aunque quitaría los debug antes de mergearlo

2020-03-31 10:04 UTC, merged