[Delivers #171293079] sala de estar mapa
Tai1Games/Programa-de-Convivencia-Espacial pull request #59
Opened 2020-03-31 11:45 UTC by JuanmaSalva

Ya se leen todos los puntos de spawn por tiled y tmb he cambiado la textura del router sry (esto obviamente es provisional)

2020-03-31 13:14 UTC, EstebenR requested changes
no me puedo agarrar a las paredes :c

2020-04-02 11:57 UTC, EstebenR approved these changes
Molto bene props al equipo

2020-04-02 12:13 UTC, eljorgemo approved these changes
Muy chido

2020-04-03 11:59 UTC, Auraum approved these changes

2020-04-03 12:23 UTC, merged