171314034 ui pelea por el mando y wi fight
Tai1Games/Programa-de-Convivencia-Espacial pull request #61
Opened 2020-04-03 20:33 UTC by Will7461

He tenido que hacer algo tricky para las barras invertidas porque no me dejaba rellenar el clip de derecha a izquierda poniendo la textura flipeada o cambiando el ángulo, por eso hay 2 barras vacias y 2 barras rellenas.

2020-04-03 21:37 UTC, EstebenR reviewed
es necesario que las progress bars funcionen por viewer? No podría manejarse la textura directamente en el renderProgressBars?

2020-04-04 10:01 UTC, AdriAlvarez00 requested changes
me salta excepción cuando el update de Hands llama a InputHandler::getStickDir(). Prueba a ver si mergeandp master se arregla

2020-04-04 13:05 UTC, EstebenR requested changes
se puede utilizar la misma textura y renderizarla varias veces por cada jugador que la necesite
es decir, no hay que crear 8 texturas si no 4 solo, y mejor pedir un puntero a la existente que crearla de todas formas, ya que se carga igualmente

2020-04-04 19:19 UTC, EstebenR approved these changes
ara si

2020-04-04 19:19 UTC, AndresRuizB approved these changes
okay

2020-04-05 09:46 UTC, AdriAlvarez00 approved these changes

2020-04-05 09:46 UTC, merged