las manos
Tai1Games/Programa-de-Convivencia-Espacial pull request #62
Opened 2020-04-04 17:49 UTC by AndresRuizB

Las manos ya se ven bien, tambien he hecho cambios en algunos sprites y en la escala
Añadido tambien un método más general a texture y adaptada la clase weapon a la nueva mano

2020-04-04 21:45 UTC, Adrian-de-Lucas-Gomez approved these changes
Están chulísimas las manos. Hay que poner eso si la escala de los objetos acorde a como salen cuando los tienes cogidos y quizas en la pelota hacerlo menos simetrico para saber mejor hacia donde giras pero por lo demás mis dieces.

2020-04-04 22:29 UTC, eljorgemo requested changes
Me gusta mucho como está quedando, en general.
¿Sería posible flippear al jugador también cuando está apuntando a la derecha?  Queda un poco raro que mire al mismo sitio siempre pero apunte a uno distinto. (Quizás comparando el ángulo de las manos con el del jugador y si el ángulo relativo > 180º entonces el jugador hace flip)
Otra opción es que la cabeza rote en dirección a donde se está apuntando, pero igual sería un poco raro cuando mira hacia abajo.

2020-04-05 18:43 UTC, AndresRuizB commented
> ¿Sería posible flippear al jugador también cuando está apuntando a la derecha? 
Un flip instantaneo queda raro, se podria estudiar lo de la cabeza, pero habria que crear otro componente creo yo

2020-04-05 18:45 UTC, eljorgemo approved these changes

2020-04-05 20:50 UTC, EstebenR approved these changes

2020-04-05 20:51 UTC, merged