HA LLEGADO EL CAPITALISMO AL PROGRAMA DE CONVIVENCIA ESPACIAL
Tai1Games/Programa-de-Convivencia-Espacial pull request #66
Opened 2020-04-05 21:43 UTC by Pj6595

**QUEDA CREADO EL MODO CAPITALISMO**

### Cambios importantes
->Los players ahora se crean en GameMode
->Los players se crean con la factoría PlayerFactory
->Ahora existe la clase coin (lleva el valor de cada coin y la activa/desactiva)
->Clase Wallet: lanza monedas cuando te hacen daño y lleva la cuenta de tus monedas
->MODO DE JUEGO CAPITALISMO: Se acaba cuando se acaba el tiempo y gana el que más monedas tenga. En caso de empate se acaba cuando haya un jugador que tenga más monedas que los demás.
->Añadidas las pools de objetos (se utilizan para las coins, aunque su tamaño no puede determinarse con una constante de json, cosas de plantillas de C++ I guess)
->La capa de colisión Weapon ahora se llama PickableObject
->**IMPORTANTE:** No hay puntos de spawn de monedas porque hay que hacer cosas con el tilemap (a saber cómo se usa eso). De momento todos los players empiezan con 10 monedas y hay que robárselas a golpes de pelota saltarina.

### Otros cambios
->Entity tiene una constructora por defecto (sin entityManager) y EntityManager ahora tiene un método para añadir entidades existentes (utilizado para incluir las entidades de pools)
->Fixes a los GameModes Pelea por el Mando y Stocks (thanks for nothing MMur)

2020-04-05 22:02 UTC, EstebenR requested changes
Muchas cosillas c:

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/EntityManager.cpp
> +	entities_.emplace_back(std::move(uPtr));
deberia ser un emplace? El emplace crea un objeto, si estamos moviendo el uPtr no deberia ser push?

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/ObjectFactory.h
> +#include "Coin.h"
Por que está todo esto en el .h y no en el cpp?

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/PCE_Project.vcxproj.filters
> +    <ClInclude Include="SRandBasedGenerator.h">
No hace falta tener un SRandBasedGenerator, con hacer rand() vale, el srand se hace en el init de SDL_Game

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/SDL_Game.cpp
> +	rng_->init();
mismo del sRandBasedGenerator, sobra

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/StocksGameMode.cpp
> +			Resources::Tinky, tilemap_->getPlayerSpawnPoint(i).x, tilemap_->getPlayerSpawnPoint(i).y, 3));
Ya tenemos sprite del jugador, no tiene por que ser Tinky

2020-04-05 22:02 UTC, EstebenR commented on src/SourceFiles/Viewer.cpp
> +		SDL_Rect r = collider_->getRectRender();
¿Para que se usa esto?

2020-04-05 22:23 UTC, mmur07 commented on src/SourceFiles/ObjectFactory.h
> +#include "Coin.h"
Qué problema hay con que esté en el .h? No lo hacemos siempre así excepto cuando pueden salir problemas de inclusividad circular?

2020-04-05 22:24 UTC, EstebenR commented on src/SourceFiles/ObjectFactory.h
> +#include "Coin.h"
Si no hay necesidad lo veo mejor en el cpp, siempre nos dicen que a menos que sea necesario mejor dejarlo en el cpp

2020-04-05 22:29 UTC, Pj6595 commented on src/SourceFiles/EntityManager.cpp
> +	entities_.emplace_back(std::move(uPtr));
Es la pool de Samir y yo no me atrevo a llevarle la contraria a Dios

2020-04-05 22:30 UTC, Pj6595 commented on src/SourceFiles/Viewer.cpp
> +		SDL_Rect r = collider_->getRectRender();
Una línea de prueba que me olvidé de borrar, no hace nada

2020-04-05 22:35 UTC, mmur07 commented
Ya están resueltos los cambios pedidos.

2020-04-05 23:12 UTC, EstebenR requested changes
Lo de las const revisadlo en otros archivos que sale en algún otro. Mañana sigo que tengo sueño, besitos

2020-04-05 23:12 UTC, EstebenR commented on src/SourceFiles/ObjectFactory.h
> +class Coin;
Si las clases no se usan en el .h al igual que no hay que incluirlas no hay que poner class. En este caso solo haria falta EntityManager que es lo unico a lo que hace mencion el ObjectFactory.h

2020-04-05 23:12 UTC, EstebenR commented on src/SourceFiles/CapitalismGameMode.cpp
> +	if (timeSinceStart >= CONST(double, "TIME_TO_END") && !roundFinished_) {
Las const pedirlas en el init y guardarlo, que es un proceso algo costoso estar pidiendolo cada ciclo ya que tiene que ir al archivo y buscarlo.

2020-04-06 11:48 UTC, EstebenR requested changes
Los personajes salen achatados, revisad el tamaño cuando los creáis

2020-04-06 11:48 UTC, EstebenR commented on src/SourceFiles/WiFightGameMode.cpp
> +			Resources::Tinky, tilemap_->getPlayerSpawnPoint(k).x, tilemap_->getPlayerSpawnPoint(k).y, 3));
Ste men sigue siendo un tinky

2020-04-06 11:48 UTC, EstebenR commented on src/SourceFiles/Wallet.cpp
> +		double y = (collPlayer_->getH(0) + CONST(double, "COIN_BASE_SIZE")) * sin(a);
Pedida de constantes

2020-04-06 11:48 UTC, EstebenR commented on src/SourceFiles/CoinsPool.h
> +#include "b2_polygon_shape.h"
include de un monton de headers, antes de simplemente cortar y pegar mirar si son todos necesarios

2020-04-06 11:48 UTC, EstebenR commented on src/SourceFiles/StocksGameMode.cpp
> +	}
Sobra este bucle?

2020-04-06 11:48 UTC, EstebenR commented on src/SourceFiles/Coin.cpp
> +		if (timeSinceDropped_ >= CONST(int, "COINS_COOLDOWN_WHEN_DROPPED")) {
consts

2020-04-06 13:01 UTC, Auraum commented on src/SourceFiles/WiFightGameMode.cpp
>  void WiFightGameMode::init(PlayState* game)
Por qué no creáis el router con el ObjectFactory?

2020-04-06 13:21 UTC, Auraum requested changes
Da error al cerrar el juego con la X y no me convence mucho que cada jugador colisione con las monedas que desprende, debería poder recuperarlas. Pero me gusta lo de que los players los haga el gameMode.

2020-04-08 17:20 UTC, Pj6595 commented
Mañana seguimos con la UI que tenemos sueño. Besitos c:

2020-04-08 17:31 UTC, EstebenR approved these changes
Molto bene, me gustaria que las roombas se dibujaran debajo de los jugadores

2020-04-08 17:41 UTC, Auraum approved these changes
muy chulo

2020-04-08 21:28 UTC, AdriAlvarez00 approved these changes
No he coseguido que se rompa
Está casi tan desbalanceado como el capitalismo de verdad <3

2020-04-08 21:29 UTC, merged