171235647 colchonetas
Tai1Games/Programa-de-Convivencia-Espacial pull request #68
Opened 2020-04-10 18:54 UTC by JuanmaSalva

Tenemos colchonetas con ANIMACION (que es un poco mierda por que no se dibujar pero bueno)

2020-04-10 20:24 UTC, EstebenR requested changes
Si el primer frame de la colchoneta es la colchoneta normal, no se podría utilizar solo la textura del spritesheet?

2020-04-10 20:24 UTC, EstebenR commented on src/SourceFiles/Pad.cpp
> +		if (frame_ / CONST(int, "PAD_ANIMATION_SPEED") == CONST(int, "PAD_ANIMATION_FRAMES")) { //ha terminado la animacion
Pedida de constantes en update

2020-04-11 14:53 UTC, JuanmaSalva commented
> Si el primer frame de la colchoneta es la colchoneta normal, no se podría utilizar solo la textura del spritesheet?

no entiendo a q te refieres. El primer frame es el estático, el resto es la animacion

2020-04-11 14:56 UTC, Pj6595 requested changes
Resulta que lo de agarrarse a la colchoneta era un bug.

2020-04-11 18:12 UTC, EstebenR approved these changes

2020-04-11 22:20 UTC, Pj6595 approved these changes

2020-04-12 08:27 UTC, AdriAlvarez00 approved these changes

2020-04-12 08:29 UTC, merged