171293102 mancuerna
Tai1Games/Programa-de-Convivencia-Espacial pull request #69
Opened 2020-04-11 11:53 UTC by Will7461

-Añadido impactDamage_ a las armas para diferenciarlo de damage_
-Nueva macro GETCMP_FROM_FIXTURE_(fixture, type); (Utilizad las macros que ya existen pls)
-Se recibe el daño de impacto del arma cuando la velocidad del arma al chocar supera la constante HIGH_DAMAGE
-La chancla no usaba MeleeWeapon, lo he comentado hasta que organicemos como van a ser las subclases de Weapon.

2020-04-11 14:36 UTC, EstebenR approved these changes
Bien, el atributo damage intuyo que es si fuera cuerpo a cuerpo?

2020-04-11 14:54 UTC, Pj6595 approved these changes

2020-04-11 17:40 UTC, mmur07 requested changes
Si en StocksGameMode vas volando hacia un arma que está quieta mueres al instante. El problema debe estar en el CollisionHandler

2020-04-11 21:04 UTC, Will7461 commented
> Bien, el atributo damage intuyo que es si fuera cuerpo a cuerpo?

Sí, se cambiará cuando tengamos las subclases

2020-04-12 17:44 UTC, JuanmaSalva commented
oka

2020-04-12 17:44 UTC, JuanmaSalva approved these changes
oka

2020-04-12 19:27 UTC, mmur07 approved these changes
Perfe

2020-04-12 20:15 UTC, merged