[delivers-#171235758] Caldera: fuego y dolor
Tai1Games/Programa-de-Convivencia-Espacial pull request #73
Opened 2020-04-12 15:23 UTC by AdriAlvarez00

Para crear una caldera usar ObjectFactory::makeBoiler()

Tres nuevas clases

- FireBallGenerator: se encarga de generar bolas de fuego alrededor de si mismo
- Fireball: equivalente a coin, se encarga de gestionar lo relacionado con el pooling
- FireballPool: ObjectPool de bolas de fuego

Cambios:
Se ha añadido un parámetro opcional fixedDamage a CollisionHandler::damageOnImpact para hacer un daño fijo independiente del objeto, por ahora solo lo usa la bola de fuego.

2020-04-12 19:48 UTC, mmur07 requested changes

2020-04-12 19:48 UTC, mmur07 commented on src/SourceFiles/ObjectFactory.cpp
> +}
Lo primero sorry por tardar tanto en hacer la review. Destaco solo un par de cosillas, el resto por lo que he visto está bastante bien. Te comento un par de cosillas no más.
El boiler usa las constantes del roomba.

2020-04-12 19:48 UTC, mmur07 commented on src/SourceFiles/CollisionHandler.cpp
> +
Esto es problemático porque la fireball colisiona con cualquier cosa que no sea una fireball. En papel está bien pero ahora mismo colisionaría con todos los triggers, incluido el trigger grande del router.

Comprueba que el fixture con el que estás colisionando no es un trigger.
>>     contact->GetFixtureA()->GetFilterData().categoryBits != Collider::CollisionLayer::Trigger;
Lo mismo para la fixture B

2020-04-13 14:59 UTC, JuanmaSalva requested changes
Lo que ha dicho miguel de las constantes de roomba en el boiler y falta el merge de master. El resto esta todo perfe

2020-04-14 09:07 UTC, JuanmaSalva approved these changes

2020-04-14 10:06 UTC, EstebenR reviewed
Se puede hacer que el fireball pool sólo se cree cuando estamos en el mapa de la caldera? Que el boiler tenga la pool ya que es lo que tiene sentido, no que todos los mapas la tengan y solo alguno la use (se puede meter por ejemplo en el FireballGenerator component).

2020-04-14 14:01 UTC, EstebenR approved these changes

2020-04-15 09:33 UTC, mmur07 approved these changes
Nice

2020-04-15 09:33 UTC, merged