172179404 tilemapSalaMaquina
Tai1Games/Programa-de-Convivencia-Espacial pull request #80
Opened 2020-04-15 15:06 UTC by JuanmaSalva

-Tile map de la sala de maquina hecho y refactor de como aparecen las armas. Siempre aparecerá un arma en una posición pero la aparición de esta es totalmente aleatoria (se tiene en cuenta que pueda salir un pistola plátano y esa así que si alguna vez no salen armas en alguna posición es por que debería salir una que no está).
-Cambiado tmb los nombres de los mapas que estaban en ESPAÑOL
-Movido la creación del boiler por que antes se generaba según el modo de juego y no la sala de estar (aparecía en el modo capitalismo aun q estuvieras en otro mapa)

2020-04-15 16:18 UTC, EstebenR requested changes
constants de armas a la parte que es de armas.
Todo lo demás correcto

2020-04-15 16:18 UTC, EstebenR commented on src/SourceFiles/TileMap.cpp
> +			ObjectFactory::makeSlipper(entityManager_, physicsWorld_, spawnPoint, b2Vec2(CONST(float, "DUMBBELL_X"), CONST(float, "DUMBBELL_Y")));
deberia ser un dumbbell no? xd

2020-04-15 16:42 UTC, EstebenR approved these changes

2020-04-16 14:52 UTC, AdriAlvarez00 requested changes

2020-04-16 14:52 UTC, AdriAlvarez00 commented on src/config/constants.json
> -}
Da error al cargar el archivo de contantes

2020-04-17 11:36 UTC, AdriAlvarez00 approved these changes

2020-04-17 15:40 UTC, Pj6595 approved these changes

2020-04-17 15:40 UTC, merged