Fixes de pools
Tai1Games/Programa-de-Convivencia-Espacial pull request #87
Opened 2020-04-18 17:05 UTC by Pj6595

Se ha limpiado un poco de código en general (ahora nos ahorramos unas cuantas líneas)

He creado el archivo PoolSizes.h para tener los tamaños de las pools controlados y no tenerlos que meter con números mágicos (por json no se pueden definir)

2020-04-18 17:12 UTC, mmur07 approved these changes
Chachi, me gusta lo de las constantes de los tamaños de las pools

2020-04-18 17:18 UTC, EstebenR requested changes
Pool Sizes al Constants.h?

2020-04-18 17:30 UTC, EstebenR approved these changes

2020-04-19 09:08 UTC, AdriAlvarez00 commented
¿Al final se habló de un metodo para desactivar las entidades que desactive al de los componentes o era sobrediseñar? Para que cada componente se encargue de su setActive

2020-04-19 11:41 UTC, JuanmaSalva reviewed
Esta perf pero petará al hacer merge por q se ha modificado master

2020-04-19 11:44 UTC, JuanmaSalva approved these changes

2020-04-19 11:54 UTC, jorgmo02 commented
@Pj6595 arregla los conflictos que si no no se puede hacer merge

2020-04-19 11:55 UTC, eljorgemo reviewed
@Pj6595 arregla los conflictos que si no no se puede hacer merge
(no quiero tocarlo yo porque en mi repo local me da problemas y no sé qué hay que dejar y qué hay que quitar)

2020-04-19 15:06 UTC, merged