Añadida invulnerabilidad
Tai1Games/Programa-de-Convivencia-Espacial pull request #92
Opened 2020-04-19 20:15 UTC by AndresRuizB

Al recibir daño y despues de recibir daño se es invulnerable durante un periodo de tiempo medido en frames

2020-04-19 20:49 UTC, EstebenR requested changes
No se pierde salud al tirar armas

2020-04-19 22:00 UTC, jorgmo02 commented
> Merge branch 'master' into 172291277-Invulnerabilidad    [b9b400b](https://github.com/Tai1Games/Programa-de-Convivencia-Espacial/pull/92/commits/b9b400bf048d8369dcfb8a417e74d47aa742c687)
Había un conflicto por el modo de juego (Timed en vez de Capitalism o algo así, imagino que no sale en el diff porque he cogido la versión de Andrés).

2020-04-20 09:20 UTC, EstebenR requested changes
Vale si que les puedo hacer daño a la gente, pero he subido los invelnerability frames hit a "1000000" y les puedo seguir haciendo daño a alguien a quien le acabo de dar

2020-04-20 17:13 UTC, JuanmaSalva approved these changes

2020-04-21 09:48 UTC, EstebenR approved these changes
Vale si funciona lo que pasa es que soy inutil

2020-04-21 11:27 UTC, AdriAlvarez00 approved these changes

2020-04-21 11:38 UTC, JuanmaSalva commented
solo tiene errores de merge por que se ha modificado master

2020-04-21 11:39 UTC, merged