172179272 tilemap gym
Tai1Games/Programa-de-Convivencia-Espacial pull request #94
Opened 2020-04-20 17:36 UTC by JuanmaSalva

2020-04-20 18:04 UTC, EstebenR requested changes
Los jugadores no spawnean en la esquina que les corresponde

2020-04-21 09:39 UTC, EstebenR approved these changes

2020-04-21 11:07 UTC, Auraum approved these changes

2020-04-21 11:08 UTC, eljorgemo requested changes
Lo que ha dicho Esteban

2020-04-21 11:08 UTC, eljorgemo approved these changes

2020-04-21 11:09 UTC, merged