Melee weapons!
Tai1Games/Programa-de-Convivencia-Espacial pull request #99
Opened 2020-04-21 15:06 UTC by EstebenR

- Creada clase ActionableWeapon, clase virtual que sirve para crear las armas que se puedan accionar, como mínimo se ha de redefinir su método *action*, implementa cooldowns

- Alterada clase ExtinguisherWeapon, ahora hereda de ActionableWeapon, por lo que no tiene que redefinir el funcionamiento del cooldown

- Creada clase MeleeWeapon, que hereda de ActionableWeapon, he trasladado la funcionalidad que habia entremezclada antes a MeleeWeapon pero acabo de comer y es un bol de espaguetis a la boloñesa que no me hace especial ilusion tragarme. La funcionalidad está falta que el ataque detecte bien

2020-04-21 19:56 UTC, mmur07 requested changes

2020-04-21 19:56 UTC, mmur07 commented on src/SourceFiles/MeleeWeapon.cpp
> +			else damage_ = calculateCoinsDropped(playerInfo_[currentHand_->getPlayerId()].playerWallet->getCoins());
Este cálculo de daño es específico de la chancla y no del resto de armas a melee.
Creo que lo óptimo en este caso sería hacer una clase Slipper que herede de MeleeWeapon y que solo cambie el action.
El action genérico de MeleeWeapon debería quitar damage_ (variable que le pasas por parámetro) puntos de vida.

2020-04-21 22:21 UTC, mmur07 approved these changes
Perfe

2020-04-22 01:14 UTC, jorgmo02 commented on src/SourceFiles/SlipperWeapon.cpp
> +	if (playerInfo_[currentHand_->getPlayerId()].playerHealth) {
no abuseis de esto que devuelve NULL, no nullptr

2020-04-22 01:23 UTC, jorgmo02 commented on src/SourceFiles/MeleeWeapon.cpp
> +	cout << "Enemigo en rango" << endl;
```suggestion
if (!beenActivated_){
	cout << "Enemigo en rango" << endl;
	
```

2020-04-22 09:01 UTC, EstebenR commented on src/SourceFiles/MeleeWeapon.cpp
> +	cout << "Enemigo en rango" << endl;
De la manera que hizo Adri el codigo es que cuando coges el arma se crea una caja de colision delante de ella y cuando entra alguien se mete a un vector.
Entonces cuando pegas aplica el daño a todo el mundo en ese vector, pero tiene que detectarlos aunque no esté habilitada para usar creo

2020-04-22 09:02 UTC, eljorgemo approved these changes

2020-04-22 11:46 UTC, JuanmaSalva requested changes
No mata al otro jugador dentro de la partida

2020-04-23 17:11 UTC, JuanmaSalva reviewed
Sigue sin dejar cadaver del jugador al que golpeas (como hace la bola de fuego o las armas al lanzarlas)

2020-04-24 08:38 UTC, JuanmaSalva approved these changes

2020-04-24 08:38 UTC, merged